# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: monitoreo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fmonitoreo.proto\"\x0b\n\tNoRequest\"\x1e\n\x0b\x45\x61syRequest\x12\x0f\n\x07package\x18\x01 \x01(\t\"1\n\x0bHardRequest\x12\x0f\n\x07package\x18\x01 \x01(\t\x12\x11\n\tcontainer\x18\x02 \x01(\t25\n\tmonitoreo\x12(\n\nvigilancia\x12\n.NoRequest\x1a\x0c.EasyRequest\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'monitoreo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NOREQUEST._serialized_start=19
  _NOREQUEST._serialized_end=30
  _EASYREQUEST._serialized_start=32
  _EASYREQUEST._serialized_end=62
  _HARDREQUEST._serialized_start=64
  _HARDREQUEST._serialized_end=113
  _MONITOREO._serialized_start=115
  _MONITOREO._serialized_end=168
# @@protoc_insertion_point(module_scope)
