# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import monitoreo_pb2 as monitoreo__pb2


class monitoreoStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.vigilancia = channel.unary_unary(
                '/monitoreo/vigilancia',
                request_serializer=monitoreo__pb2.NoRequest.SerializeToString,
                response_deserializer=monitoreo__pb2.EasyRequest.FromString,
                )


class monitoreoServicer(object):
    """Missing associated documentation comment in .proto file."""

    def vigilancia(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_monitoreoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'vigilancia': grpc.unary_unary_rpc_method_handler(
                    servicer.vigilancia,
                    request_deserializer=monitoreo__pb2.NoRequest.FromString,
                    response_serializer=monitoreo__pb2.EasyRequest.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'monitoreo', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class monitoreo(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def vigilancia(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/monitoreo/vigilancia',
            monitoreo__pb2.NoRequest.SerializeToString,
            monitoreo__pb2.EasyRequest.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
