# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: controller.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63ontroller.proto\"\x06\n\x04Nada\"2\n\x08Response\x12\x13\n\x0bstatus_code\x18\x01 \x01(\x05\x12\x11\n\tcpu_usage\x18\x02 \x01(\x05\x32(\n\ncontroller\x12\x1a\n\x04Ping\x12\x05.Nada\x1a\t.Response\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'controller_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NADA._serialized_start=20
  _NADA._serialized_end=26
  _RESPONSE._serialized_start=28
  _RESPONSE._serialized_end=78
  _CONTROLLER._serialized_start=80
  _CONTROLLER._serialized_end=120
# @@protoc_insertion_point(module_scope)
